---
# Docker-specific variables

docker_edition: ce
docker_compose_version: "2"

# User to add to the docker group (defaults to ansible_user)
docker_user: "{{ ansible_user }}"

# Docker daemon configuration
docker_daemon_options:
  log-driver: "json-file"
  log-opts:
    max-size: "100m"
    max-file: "3"
